/**
 * CAREERMARG (DISHA V2) - Comprehensive Assessment Data & Question Bank
 * Includes:
 * 1. Tier 1 (Core): Comprehensive Holland RIASEC Interest Battery (42 Standard Questions - 7 per trait from JECRC/QuizAcademy)
 * 2. Tier 1 (Fast-Track): Quick RIASEC Career Pulse (24 Questions - 4 per trait for rapid 5-min discovery)
 * 3. Tier 2: NCERT TAMANNA Cognitive Aptitude Battery (28 Questions - 4 per domain)
 * 4. Tier 3: Big Five (OCEAN) Personality Dynamics (20 Questions - 4 per trait)
 * 5. Tier 4: Exam Stress & Setback Resilience Index (12 Questions - 4 per dimension)
 * 6. Mind Gym & Stress Relief Protocols
 */

const LIKERT_5 = [
  { id: "1", text: "Strongly Disagree", textHi: "पूरी तरह असहमत" },
  { id: "2", text: "Disagree", textHi: "असहमत" },
  { id: "3", text: "Neutral / Unsure", textHi: "तटस्थ / अनिश्चित" },
  { id: "4", text: "Agree", textHi: "सहमत" },
  { id: "5", text: "Strongly Agree", textHi: "पूरी तरह सहमत" },
];

const RIASEC_OPTIONS = LIKERT_5;

const DISHA_ASSESSMENT_TRAITS = {
  // RIASEC Holland Code Traits
  R: {
    code: "R",
    tier: "tier1_riasec",
    name: "Realistic (Doers)",
    nameHi: "व्यावहारिक (डूअर्स)",
    icon: "🔧",
    color: "#f59e0b",
    description: "Hands-on, practical, mechanical, tools, and outdoor tasks.",
    descriptionHi: "प्रैक्टिकल, तकनीकी, मशीनरी और ग्राउंड-लेवल कार्यों में रुचि।",
    fact: "Engineers, pilots, surgeons, and robotics experts have strong 'Realistic' traits.",
    factHi: "इंजीनियर, पायलट, सर्जन और रोबोटिक्स विशेषज्ञों में 'Realistic' गुण प्रमुख होता है।",
  },
  I: {
    code: "I",
    tier: "tier1_riasec",
    name: "Investigative (Thinkers)",
    nameHi: "खोजी / विश्लेषणात्मक (थिंकर्स)",
    icon: "🔬",
    color: "#3b82f6",
    description: "Scientific curiosity, research, analysis, and abstract problem solving.",
    descriptionHi: "वैज्ञानिक जिज्ञासा, शोध, डेटा विश्लेषण और तार्किक समाधान।",
    fact: "Data scientists, astronomers, and doctors thrive on Investigative inquiry.",
    factHi: "डेटा वैज्ञानिक, खगोलशास्त्री और चिकित्सक खोजी स्वभाव से नई ऊंचाइयां छूते हैं।",
  },
  A: {
    code: "A",
    tier: "tier1_riasec",
    name: "Artistic (Creators)",
    nameHi: "रचनात्मक / कलात्मक (क्रिएटर्स)",
    icon: "🎨",
    color: "#ec4899",
    description: "Creative self-expression, design, storytelling, media, and visual arts.",
    descriptionHi: "कला, डिजाइनिंग, संगीत, लेखन, एनीमेशन और रचनात्मक अभिव्यक्ति।",
    fact: "UX designers, filmmakers, and architects blend Artistic flair with practical vision.",
    factHi: "यूआई/यूएक्स डिजाइनर, फिल्म निर्माता और आर्किटेक्ट कलात्मक सोच से नवाचार करते हैं।",
  },
  S: {
    code: "S",
    tier: "tier1_riasec",
    name: "Social (Helpers)",
    nameHi: "सामाजिक / सहायक (हेल्पर्स)",
    icon: "🤝",
    color: "#10b981",
    description: "Teaching, mentoring, healthcare, guidance, and community service.",
    descriptionHi: "मार्गदर्शन, अध्यापन, परामर्श, स्वास्थ्य सेवा और समाज सुधार।",
    fact: "Educators, psychologists, and NGO leaders excel with high Social empathy.",
    factHi: "शिक्षक, मनोवैज्ञानिक और सामाजिक मार्गदर्शक गहरी सहानुभूति के साथ काम करते हैं।",
  },
  E: {
    code: "E",
    tier: "tier1_riasec",
    name: "Enterprising (Persuaders)",
    nameHi: "उद्यमी / मार्गदर्शक (लीडर्स)",
    icon: "⚡",
    color: "#8b5cf6",
    description: "Leadership, entrepreneurship, public speaking, negotiation, and strategy.",
    descriptionHi: "नेतृत्व, स्टार्टअप, सार्वजनिक प्रस्तुति, बातचीत और व्यापारिक रणनीति।",
    fact: "CEOs, startup founders, and policymakers lead through Enterprising vision.",
    factHi: "सीईओ, स्टार्टअप संस्थापक और नीति निर्माता एंटरप्राइजिंग विजन से नेतृत्व करते हैं।",
  },
  C: {
    code: "C",
    tier: "tier1_riasec",
    name: "Conventional (Organizers)",
    nameHi: "संगठनात्मक / व्यवस्थित (ऑर्गनाइजर्स)",
    icon: "📋",
    color: "#06b6d4",
    description: "Systematic organization, structured processes, data accuracy, and precision.",
    descriptionHi: "सुव्यवस्थित प्रणाली, रिकॉर्ड कीपिंग, डेटा सटीकता और वित्तीय प्रबंधन।",
    fact: "Chartered accountants, supply chain heads, and forensic auditors master Conventional order.",
    factHi: "सीए, वित्तीय विश्लेषक और सिस्टम मैनेजर सटीकता व अनुशासन से काम करते हैं।",
  },

  // Tier 2: NCERT TAMANNA Multi-Aptitude
  TAMANNA_LA: {
    code: "TAMANNA_LA",
    tier: "tier2_tamanna",
    name: "Language Aptitude (LA)",
    nameHi: "भाषा योग्यता (LA)",
    icon: "📖",
    color: "#2563eb",
    description: "Verbal comprehension, grammar logic, vocabulary mastery, and linguistic speed.",
    descriptionHi: "शब्दावली, वाक्य संरचना और भाषाई अभिव्यक्ति में निपुणता।",
  },
  TAMANNA_VA: {
    code: "TAMANNA_VA",
    tier: "tier2_tamanna",
    name: "Abstract Reasoning (VA)",
    nameHi: "अमूर्त तर्क (VA)",
    icon: "🧩",
    color: "#4f46e5",
    description: "Visual logic, sequence recognition, pattern completion, and conceptual problem solving.",
    descriptionHi: "पैटर्न पहचान, तार्किक आकृतियों का विश्लेषण और समस्या समाधान।",
  },
  TAMANNA_NA: {
    code: "TAMANNA_NA",
    tier: "tier2_tamanna",
    name: "Numerical Aptitude (NA)",
    nameHi: "संख्यात्मक योग्यता (NA)",
    icon: "🔢",
    color: "#059669",
    description: "Arithmetic calculations, quantitative interpretation, and mathematical reasoning.",
    descriptionHi: "अंकगणित, डेटा व्याख्या और गणितीय समीकरणों को हल करने की क्षमता।",
  },
  TAMANNA_SA: {
    code: "TAMANNA_SA",
    tier: "tier2_tamanna",
    name: "Spatial Aptitude (SA)",
    nameHi: "स्थानिक योग्यता (SA)",
    icon: "📐",
    color: "#7c3aed",
    description: "3D mental manipulation, geometric rotation, structural visualization, and blueprints.",
    descriptionHi: "3D मानसिक कल्पना, ज्यामितीय घुमाव और संरचनात्मक दृष्टि।",
  },
  TAMANNA_PA: {
    code: "TAMANNA_PA",
    tier: "tier2_tamanna",
    name: "Perceptual Aptitude (PA)",
    nameHi: "अवधारणात्मक योग्यता (PA)",
    icon: "👁️",
    color: "#db2777",
    description: "Visual precision, rapid error detection, detail scanning, and symbol recognition.",
    descriptionHi: "बारीकियों को तेजी से पकड़ने और दृश्य सटीकता की क्षमता।",
  },
  TAMANNA_MA: {
    code: "TAMANNA_MA",
    tier: "tier2_tamanna",
    name: "Mechanical Aptitude (MA)",
    nameHi: "यांत्रिक योग्यता (MA)",
    icon: "⚙️",
    color: "#ea580c",
    description: "Intuition for gears, physical forces, pulleys, levers, kinematics, and energy transfer.",
    descriptionHi: "गियर, पुली, लीवर और भौतिक बलों के कामकाज की प्राकृतिक समझ।",
  },
  TAMANNA_AR: {
    code: "TAMANNA_AR",
    tier: "tier2_tamanna",
    name: "Aptitude Reasoning (AR)",
    nameHi: "समग्र तार्किक योग्यता (AR)",
    icon: "🧠",
    color: "#0284c7",
    description: "Deductive & inductive logic, condition mapping, and critical hypothesis testing.",
    descriptionHi: "निगमनात्मक तर्क, तार्किक निष्कर्ष और गहरी विश्लेषणात्मक क्षमता।",
  },

  // Tier 3: Big Five OCEAN Personality
  OCEAN_O: {
    code: "OCEAN_O",
    tier: "tier3_ocean",
    name: "Openness to Experience",
    nameHi: "नए अनुभवों के प्रति खुलापन",
    icon: "💡",
    color: "#8b5cf6",
    description: "Intellectual curiosity, creative experimentation, and appetite for emerging concepts.",
    descriptionHi: "जिज्ञासा, नई तकनीकों को आजमाने का साहस और कलात्मक सोच।",
  },
  OCEAN_C: {
    code: "OCEAN_C",
    tier: "tier3_ocean",
    name: "Conscientiousness",
    nameHi: "कर्तव्यनिष्ठा व अनुशासन",
    icon: "🎯",
    color: "#10b981",
    description: "Self-discipline, organization, punctuality, and methodical goal execution.",
    descriptionHi: "लक्ष्य के प्रति समर्पण, समयबद्धता और अनुशासित जीवनशैली।",
  },
  OCEAN_E: {
    code: "OCEAN_E",
    tier: "tier3_ocean",
    name: "Extraversion",
    nameHi: "बहिर्मुखता व सामाजिक ऊर्जा",
    icon: "🗣️",
    color: "#f59e0b",
    description: "Social vibrancy, team assertiveness, energetic communication, and group initiative.",
    descriptionHi: "लोगों के बीच ऊर्जा, स्पष्ट संवाद और दल का नेतृत्व करने का उत्साह।",
  },
  OCEAN_A: {
    code: "OCEAN_A",
    tier: "tier3_ocean",
    name: "Agreeableness",
    nameHi: "सहानुभूति व सहयोग",
    icon: "❤️",
    color: "#ec4899",
    description: "Empathy, trust, conflict mediation, altruism, and constructive teamwork.",
    descriptionHi: "सहकार्यता, दूसरों के दृष्टिकोण को समझना और सौहार्दपूर्ण व्यवहार।",
  },
  OCEAN_N: {
    code: "OCEAN_N",
    tier: "tier3_ocean",
    name: "Emotional Stability",
    nameHi: "भावनात्मक संतुलन व स्थिरता",
    icon: "🛡️",
    color: "#3b82f6",
    description: "Calmness under examination pressure, emotional fortitude, and steady resilience.",
    descriptionHi: "दबाव में संयम, घबराहट पर नियंत्रण और आत्मविश्वास बनाए रखना।",
  },

  // Tier 4: Mental Health & Resilience
  ENABLER_ANXIETY: {
    code: "ENABLER_ANXIETY",
    tier: "mental_health",
    name: "Exam & Academic Anxiety",
    nameHi: "परीक्षा तनाव व चिंता",
    icon: "🧘",
    color: "#ef4444",
    description: "Measures test-taking stress, fear of negative evaluation, and physiological arousal.",
    descriptionHi: "परीक्षा से जुड़ा दबाव, प्रदर्शन का डर और तनाव प्रबंधन स्तर।",
  },
  ENABLER_SELF_EFFICACY: {
    code: "ENABLER_SELF_EFFICACY",
    tier: "mental_health",
    name: "Academic Self-Efficacy",
    nameHi: "आत्म-प्रभावकारिता व विश्वास",
    icon: "🌟",
    color: "#f59e0b",
    description: "Belief in one's capability to overcome academic hurdles and master tough subjects.",
    descriptionHi: "कठिन विषयों को सीखने और चुनौतियों से पार पाने का आंतरिक विश्वास।",
  },
  ENABLER_RESILIENCE: {
    code: "ENABLER_RESILIENCE",
    tier: "mental_health",
    name: "Setback Resilience",
    nameHi: "धैर्य व मानसिक लचीलापन",
    icon: "💪",
    color: "#10b981",
    description: "Ability to bounce back from low marks, adapt to setbacks, and maintain optimism.",
    descriptionHi: "कम अंकों या असफलताओं के बाद फिर से खड़े होने का सकारात्मक हौसला।",
  },
};

const DISHA_ALL_QUESTIONS = [
  // ===================== TIER 1 (CORE): RIASEC COMPREHENSIVE (42 Questions) =====================
  {
    id: "ria-01",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like to work on cars",
    questionTextHi: "मुझे कारों, गाड़ियों और मैकेनिकल उपकरणों पर काम करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-02",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I like to do puzzles",
    questionTextHi: "मुझे पहेलियाँ, तार्किक पज़ल्स और दिमागी चुनौतियाँ हल करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-03",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I am good at working independently",
    questionTextHi: "मैं स्वतंत्र रूप से और अपनी रचनात्मक सोच के साथ काम करने में कुशल हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-04",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like to work in teams",
    questionTextHi: "मुझे टीम में मिलकर काम करना और दूसरों के साथ सहयोग करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-05",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I am an ambitious person, I set goals for myself",
    questionTextHi: "मैं एक महत्वाकांक्षी व्यक्ति हूँ और अपने लिए बड़े लक्ष्य निर्धारित करता/करती हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-06",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I like to organize things (files, desks/offices)",
    questionTextHi: "मुझे चीजों को व्यवस्थित और सुव्यवस्थित रखना पसंद है (जैसे फाइलें, डेस्क और ऑफिस)।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-07",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like to build things",
    questionTextHi: "मुझे अपने हाथों से नई चीजें और संरचनाएं बनाना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-08",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I like to read about art and music",
    questionTextHi: "मुझे कला, चित्रकला, साहित्य और संगीत के बारे में पढ़ना व जानना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-09",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I like to have clear instructions to follow",
    questionTextHi: "मुझे काम करने के लिए स्पष्ट नियम और तय निर्देशों का पालन करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-10",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I like to try to influence or persuade people",
    questionTextHi: "मुझे लोगों को प्रेरित करना या अपनी बात से सहमत कराना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-11",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I like to do experiments",
    questionTextHi: "मुझे वैज्ञानिक प्रयोग करना और नए तथ्यों की खोज करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-12",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like to teach or train people",
    questionTextHi: "मुझे दूसरों को नई चीजें सिखाना, पढ़ाना या ट्रेनिंग देना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-13",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like trying to help people solve their problems",
    questionTextHi: "मुझे लोगों की व्यक्तिगत या सामाजिक समस्याओं को सुलझाने में मदद करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-14",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like to take care of animals",
    questionTextHi: "मुझे पशु-पक्षियों, प्रकृति और जानवरों की देखभाल करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-15",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I wouldn't mind working 8 hours per day in an office",
    questionTextHi: "मुझे ऑफिस में बैठकर रोजाना 8 घंटे संरचित काम करने में कोई झिझक नहीं है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-16",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I like selling things",
    questionTextHi: "मुझे सामान या आइडियाज बेचना और व्यापारिक सौदे करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-17",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I enjoy creative writing",
    questionTextHi: "मुझे रचनात्मक लेखन, कहानियां, कविताएं या ब्लॉग लिखना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-18",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I enjoy science",
    questionTextHi: "मुझे विज्ञान, अनुसंधान और नई टेक्नोलॉजी की गहरी समझ में रुचि है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-19",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I am quick to take on new responsibilities",
    questionTextHi: "मैं नई जिम्मेदारियां और लीडरशिप की भूमिकाएं लेने में तत्पर रहता/रहती हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-20",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I am interested in healing people",
    questionTextHi: "मुझे बीमार या जरूरतमंद लोगों की चिकित्सा व स्वास्थ्य सुधार में मदद करने में रुचि है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-21",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I enjoy trying to figure out how things work",
    questionTextHi: "मुझे यह समझना और विश्लेषण करना पसंद है कि मशीनें और प्रणालियाँ अंदर से कैसे काम करती हैं।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-22",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like putting things together or assembling things",
    questionTextHi: "मुझे पार्ट्स को जोड़ना, असेंबल करना और टूटे हुए उपकरणों को ठीक करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-23",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I am a creative person",
    questionTextHi: "मैं एक अत्यंत रचनात्मक और कल्पनाशील व्यक्ति हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-24",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I pay attention to details",
    questionTextHi: "मैं हर काम में छोटी-छोटी बारीकियों और शुद्धता पर विशेष ध्यान देता/देती हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-25",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I like to do filing or typing",
    questionTextHi: "मुझे फाइलों का प्रबंधन, टाइपिंग और डेटा का रिकॉर्ड रखना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-26",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I like to analyze things (problems/situations)",
    questionTextHi: "मुझे जटिल समस्याओं और डेटा का गहन तार्किक विश्लेषण करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-27",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I like to play instruments or sing",
    questionTextHi: "मुझे संगीत वाद्ययंत्र बजाना, गाना गाना या धुनें बनाना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-28",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I enjoy learning about other cultures",
    questionTextHi: "मुझे विभिन्न संस्कृतियों, परंपराओं और समाजों के बारे में जानना व सीखना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-29",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I would like to start my own business",
    questionTextHi: "मैं भविष्य में अपना खुद का व्यवसाय या उद्यम (Startup) शुरू करना चाहता/चाहती हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-30",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like to cook",
    questionTextHi: "मुझे खाना बनाना और पाक-कला के नए प्रयोग करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-31",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I like acting in plays",
    questionTextHi: "मुझे नाटकों, मंच प्रस्तुतियों या फिल्मों में अभिनय करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-32",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I am a practical person",
    questionTextHi: "मैं एक यथार्थवादी और व्यावहारिक व्यक्ति हूँ जो ठोस परिणामों पर विश्वास करता है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-33",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I like working with numbers or charts",
    questionTextHi: "मुझे संख्याओं, ग्राफ्स और गणितीय डेटा के साथ काम करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-34",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like to get into discussions about issues",
    questionTextHi: "मुझे सामाजिक और समकालीन मुद्दों पर विचार-विमर्श व सार्थक चर्चा करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-35",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I am good at keeping records of my work",
    questionTextHi: "मैं अपने काम, खर्च और समय-सारणी का सटीक रिकॉर्ड रखने में माहिर हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-36",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I like to lead",
    questionTextHi: "मुझे किसी समूह या प्रोजेक्ट का नेतृत्व करना और दिशा दिखाना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-37",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like working outdoors",
    questionTextHi: "मुझे खुली प्रकृति, मैदानों और आउटडोर वातावरण में काम करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-38",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I would like to work in an office",
    questionTextHi: "मुझे एक सुव्यवस्थित और शांत कॉर्पोरेट ऑफिस में काम करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-39",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I'm good at math",
    questionTextHi: "मेरी गणितीय और तार्किक गणना क्षमता बहुत अच्छी है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-40",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like helping people",
    questionTextHi: "मुझे जरूरतमंद लोगों की मदद और समाज सेवा करने में आत्मसंतुष्टि मिलती है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-41",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I like to draw",
    questionTextHi: "मुझे रेखाचित्र (Drawing), पेंटिंग या डिजाइन बनाना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "ria-42",
    tier: "tier1_riasec",
    submodule: "riasec_comprehensive",
    submoduleTitle: "Comprehensive Holland RIASEC Battery",
    submoduleTitleHi: "विस्तृत हॉलैंड कोड रुचि इन्वेंट्री",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I like to give speeches",
    questionTextHi: "मुझे सार्वजनिक भाषण देना और लोगों के सामने अपनी बात प्रभावशाली ढंग से रखना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },

  // ===================== TIER 1 (FAST-TRACK): QUICK RIASEC PULSE (24 Questions) =====================
  {
    id: "qria-01",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like to work on cars and mechanical machines",
    questionTextHi: "मुझे कारों, गाड़ियों और मैकेनिकल मशीनों पर काम करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-02",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like to build things with my hands",
    questionTextHi: "मुझे अपने हाथों से नई चीजें बनाना और निर्माण कार्य करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-03",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like to take care of animals and work outdoors",
    questionTextHi: "मुझे पशु-पक्षियों की देखभाल करना और आउटडोर वातावरण में काम करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-04",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "R",
    traitTitle: "Realistic",
    traitTitleHi: "व्यावहारिक (डूअर्स)",
    questionText: "I like assembling or repairing devices and gadgets",
    questionTextHi: "मुझे पुर्जों को जोड़ना, असेंबल करना और टूटे हुए उपकरणों को ठीक करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-05",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I like to do puzzles and brain teasers",
    questionTextHi: "मुझे पहेलियाँ, तार्किक पज़ल्स और दिमागी चुनौतियाँ हल करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-06",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I like to do scientific experiments and discoveries",
    questionTextHi: "मुझे वैज्ञानिक प्रयोग करना और नए वैज्ञानिक तथ्यों की खोज करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-07",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I enjoy science and exploring complex questions",
    questionTextHi: "मुझे विज्ञान, अनुसंधान और नई टेक्नोलॉजी की गहरी समझ में रुचि है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-08",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "I",
    traitTitle: "Investigative",
    traitTitleHi: "खोजी / विश्लेषणात्मक",
    questionText: "I enjoy figuring out how complicated systems work",
    questionTextHi: "मुझे यह समझना और विश्लेषण करना पसंद है कि जटिल प्रणालियाँ अंदर से कैसे काम करती हैं।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-09",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I am good at creative and independent work",
    questionTextHi: "मैं स्वतंत्र रूप से और अपनी रचनात्मक सोच के साथ काम करने में कुशल हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-10",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I like to read about art, music, and design",
    questionTextHi: "मुझे कला, चित्रकला, साहित्य और संगीत के बारे में पढ़ना व जानना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-11",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I enjoy creative writing, stories, and expressions",
    questionTextHi: "मुझे रचनात्मक लेखन, कहानियां, कविताएं या ब्लॉग लिखना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-12",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "A",
    traitTitle: "Artistic",
    traitTitleHi: "रचनात्मक / कलात्मक",
    questionText: "I am an imaginative and artistic creator",
    questionTextHi: "मैं एक अत्यंत रचनात्मक और कल्पनाशील व्यक्ति हूँ जो नए विचार गढ़ता है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-13",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like to work in collaborative teams",
    questionTextHi: "मुझे टीम में मिलकर काम करना और दूसरों के साथ सहयोग करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-14",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like to teach, train, and guide students",
    questionTextHi: "मुझे दूसरों को नई चीजें सिखाना, पढ़ाना या ट्रेनिंग देना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-15",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I like trying to help people solve their life problems",
    questionTextHi: "मुझे लोगों की व्यक्तिगत या सामाजिक समस्याओं को सुलझाने में मदद करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-16",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "S",
    traitTitle: "Social",
    traitTitleHi: "सामाजिक / सहायक",
    questionText: "I am interested in healthcare, healing, and counseling",
    questionTextHi: "मुझे बीमार या जरूरतमंद लोगों की चिकित्सा, परामर्श व स्वास्थ्य सुधार में मदद करने में रुचि है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-17",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I am an ambitious person with big leadership goals",
    questionTextHi: "मैं एक महत्वाकांक्षी व्यक्ति हूँ और अपने लिए बड़े लक्ष्य निर्धारित करता/करती हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-18",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I like to influence, lead, and persuade people",
    questionTextHi: "मुझे लोगों को प्रेरित करना, नेतृत्व करना और अपनी बात से सहमत कराना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-19",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I like selling products, ideas, and negotiating deals",
    questionTextHi: "मुझे सामान या आइडियाज बेचना और व्यापारिक सौदे करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-20",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "E",
    traitTitle: "Enterprising",
    traitTitleHi: "उद्यमी / मार्गदर्शक",
    questionText: "I am quick to take on new strategic responsibilities",
    questionTextHi: "मैं नई जिम्मेदारियां और लीडरशिप की भूमिकाएं लेने में हमेशा तत्पर रहता/रहती हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-21",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I like to organize files, desks, and databases",
    questionTextHi: "मुझे चीजों को व्यवस्थित और सुव्यवस्थित रखना पसंद है (जैसे फाइलें, डेस्क और ऑफिस)।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-22",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I like following clear rules and systematic workflows",
    questionTextHi: "मुझे काम करने के लिए स्पष्ट नियम और तय निर्देशों का पालन करना पसंद है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-23",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I wouldn't mind working in a structured corporate office",
    questionTextHi: "मुझे ऑफिस में बैठकर रोजाना संरचित कार्य करने में कोई झिझक नहीं है।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },
  {
    id: "qria-24",
    tier: "tier1_quick_riasec",
    submodule: "riasec_fast_track",
    submoduleTitle: "Quick RIASEC Career Pulse",
    submoduleTitleHi: "त्वरित करियर पल्स - आरआईएएसईसी",
    traitCode: "C",
    traitTitle: "Conventional",
    traitTitleHi: "संगठनात्मक / व्यवस्थित",
    questionText: "I pay great attention to accuracy and fine details",
    questionTextHi: "मैं हर काम में छोटी-छोटी बारीकियों और शुद्धता पर विशेष ध्यान देता/देती हूँ।",
    type: "likert_5",
    options: RIASEC_OPTIONS,
  },

  // ===================== TIER 2: NCERT TAMANNA APTITUDE (28 Questions) =====================
  {
    id: "tam-01",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_LA",
    questionText: "I quickly pick up new vocabulary, grammatical nuances, and linguistic idioms.",
    questionTextHi: "मैं नए शब्द, व्याकरण के नियम और मुहावरे बहुत जल्दी समझ और सीख लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-02",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_LA",
    questionText: "I can articulate complex arguments clearly in writing with appropriate tone and structure.",
    questionTextHi: "मैं जटिल विचारों को लिखित रूप में स्पष्ट, सटीक और प्रभावशाली ढंग से व्यक्त कर सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-03",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_LA",
    questionText: "When reading dense editorial passages or legal texts, I easily grasp the main theme and tone.",
    questionTextHi: "कठिन संपादकीय या तकनीकी गद्यांश पढ़ते समय मैं मुख्य सारांश और भाव आसानी से समझ लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-04",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_LA",
    questionText: "I enjoy translating ideas between languages (e.g. Hindi & English) without losing subtle meaning.",
    questionTextHi: "मुझे हिंदी और अंग्रेज़ी के बीच सटीक अर्थ बनाए रखते हुए विचारों का अनुवाद करना पसंद है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-05",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_VA",
    questionText: "I can easily deduce analogies (e.g. 'Microscope is to Biologist as Telescope is to Astronomer').",
    questionTextHi: "मैं शाब्दिक संबंधों और उपमाओं को बहुत आसानी से समझ लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-06",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_VA",
    questionText: "I spot logical fallacies or contradictions in spoken debates very quickly.",
    questionTextHi: "मैं बातचीत या बहस में तार्किक त्रुटियों और विरोधाभासों को तुरंत पहचान लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-07",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_VA",
    questionText: "I am strong at syllogisms and deductive word puzzles (Statement-Conclusion logic).",
    questionTextHi: "मैं कथन-निष्कर्ष और तार्किक शब्द पहेलियों को हल करने में निपुण हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-08",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_VA",
    questionText: "I can summarize a 10-page complex topic into 3 crystal-clear spoken bullet points.",
    questionTextHi: "मैं किसी लंबे और जटिल विषय को 3 स्पष्ट मौखिक बिंदुओं में संक्षिप्त कर सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-09",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_NA",
    questionText: "I perform mental arithmetic (percentages, ratios, series) quickly without a calculator.",
    questionTextHi: "मैं बिना कैलकुलेटर के प्रतिशत, अनुपात और संख्या अनुक्रम की गणना तेज़ी से कर लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-10",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_NA",
    questionText: "I find patterns in number sequences (e.g., 2, 6, 12, 20, 30...) effortlessly.",
    questionTextHi: "मैं संख्या अनुक्रमों में छिपे गणितीय पैटर्न को आसानी से पहचान लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-11",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_NA",
    questionText: "I interpret bar charts, pie diagrams, and statistical tables rapidly during tests.",
    questionTextHi: "मैं पाई चार्ट, बार ग्राफ और सांख्यिकीय तालिकाओं से तुरंत सही निष्कर्ष निकाल लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-12",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_NA",
    questionText: "I enjoy applying algebraic formulas and probability to solve real-world optimization problems.",
    questionTextHi: "मुझे वास्तविक जीवन की समस्याओं को बीजगणित और प्रायिकता (Probability) से हल करना पसंद है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-13",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_SA",
    questionText: "I can mentally rotate 3D geometric shapes and imagine them from different angles.",
    questionTextHi: "मैं अपने मन में 3D आकृतियों को घुमाकर विभिन्न कोणों से आसानी से देख सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-14",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_SA",
    questionText: "I navigate city routes, maps, and blueprints intuitively without getting disoriented.",
    questionTextHi: "मैं नक्शों, ब्लूप्रिंट और रास्तों को बिना भ्रमित हुए बहुत अच्छी तरह समझ लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-15",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_SA",
    questionText: "I can visualize how a flat sheet of paper folds into an origami box or cube.",
    questionTextHi: "मैं कागज़ के समतल टुकड़े को मोड़ने पर बनने वाले बॉक्स या क्यूब की कल्पना कर सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-16",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_SA",
    questionText: "I can judge distances, clearances, and structural proportions with sharp visual accuracy.",
    questionTextHi: "मैं दूरी, ऊंचाई और वस्तुओं के अनुपात का सटीक विज़ुअल अनुमान लगा लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-17",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_PA",
    questionText: "I can spot tiny differences, spelling typos, or symbol mismatches in large tables rapidly.",
    questionTextHi: "मैं बड़े डेटासेट में छोटी से छोटी त्रुटि या अंतर बहुत तेज़ी से पहचान लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-18",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_PA",
    questionText: "When comparing two complex diagrams side-by-side, I identify the variations in seconds.",
    questionTextHi: "दो चित्रों की तुलना करते समय मैं कुछ ही सेकंड में दोनों का अंतर पकड़ लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-19",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_PA",
    questionText: "I maintain high speed and zero careless errors when copying or checking lists under timer pressure.",
    questionTextHi: "समय सीमा के दबाव में भी मैं बिना किसी लापरवाही के तेज़ गति से सही काम करता/करती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-20",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_PA",
    questionText: "I excel at matching codes, serial numbers, and symbols with razor-sharp focus.",
    questionTextHi: "मैं सीरियल नंबर, कोड्स और प्रतीकों के मिलान में अत्यधिक एकाग्र रहता/रहती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-21",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_MA",
    questionText: "I intuitively understand how pulleys, gear ratios, levers, and torque work in physical systems.",
    questionTextHi: "मैं पुली, गियर, लीवर और टॉर्क के भौतिक नियमों को सहजता से समझ लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-22",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_MA",
    questionText: "If a gear rotates clockwise, I can deduce which direction connected gears will turn.",
    questionTextHi: "यदि एक गियर क्लॉकवाइज़ घूमता है, तो मैं जुड़े अन्य गियरों की दिशा तुरंत बता सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-23",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_MA",
    questionText: "I can troubleshoot why a physical mechanism (bicycle chain, fan motor, water pump) is jammed.",
    questionTextHi: "मैं पहचान सकता/सकती हूँ कि साइकिल चेन, मोटर या पंप में क्या खराबी आई है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-24",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_MA",
    questionText: "I enjoy learning about energy conversion, aerodynamics, and hydraulic pressure principles.",
    questionTextHi: "मुझे ऊर्जा रूपांतरण, वायुगतिकी (Aerodynamics) और हाइड्रोलिक दबाव के सिद्धांत सीखना पसंद है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-25",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_AR",
    questionText: "I solve non-verbal diagram matrices (identifying the missing pattern in a 3x3 grid) with ease.",
    questionTextHi: "मैं 3x3 ग्रिड में आकृतियों के अमूर्त पैटर्न की पहचान आसानी से कर लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-26",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_AR",
    questionText: "I can derive general underlying principles from isolated abstract observations.",
    questionTextHi: "मैं अलग-अलग अवलोकनों से मुख्य तार्किक नियम और सिद्धांत तैयार कर सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-27",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_AR",
    questionText: "When faced with a brand-new unfamiliar problem type, I adapt and invent a logic flow rapidly.",
    questionTextHi: "अपरिचित समस्या आने पर मैं तुरंत नया तार्किक दृष्टिकोण विकसित कर लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "tam-28",
    tier: "tier2_tamanna",
    submodule: "tamanna_aptitude",
    submoduleTitle: "NCERT TAMANNA Aptitude Battery",
    submoduleTitleHi: "एनसीईआरटी तमन्ना अभिक्षमता परीक्षण",
    traitCode: "TAMANNA_AR",
    questionText: "I enjoy working with flowcharts, decision trees, and conceptual algorithm diagrams.",
    questionTextHi: "मुझे फ्लोचार्ट, डिसीजन ट्री और वैचारिक एल्गोरिदम डायग्राम के साथ काम करना पसंद है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },

  // ===================== TIER 3: BIG FIVE OCEAN PERSONALITY (20 Questions) =====================
  {
    id: "oce-01",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_O",
    questionText: "I am always curious to learn emerging concepts, foreign cultures, and novel philosophies.",
    questionTextHi: "मैं नई तकनीकों, विभिन्न संस्कृतियों और नए विचारों को सीखने के लिए हमेशा उत्सुक रहता/रहती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-02",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_O",
    questionText: "I have a vivid imagination and enjoy thinking about future possibilities and innovations.",
    questionTextHi: "मेरी कल्पनाशीलता तीव्र है और मुझे भविष्य के आविष्कारों व संभावनाओं पर विचार करना पसंद है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-03",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_O",
    questionText: "I like trying unconventional study methods rather than sticking solely to traditional rote routines.",
    questionTextHi: "मैं केवल रटने के बजाय नए और रचनात्मक तरीकों से पढ़ना पसंद करता/करती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-04",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_O",
    questionText: "I find deep fascination in exploring interdisciplinary subjects that connect science with art.",
    questionTextHi: "मुझे विज्ञान, कला और समाज को आपस में जोड़ने वाले नए विषयों में गहरी रुचि है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-05",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_C",
    questionText: "I stick to my study timetable consistently, avoiding procrastination even without supervision.",
    questionTextHi: "मैं बिना किसी के कहे भी अपने अध्ययन कार्यक्रम का नियमित रूप से पालन करता/करती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-06",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_C",
    questionText: "I double-check my assignments thoroughly before submitting to ensure zero errors.",
    questionTextHi: "मैं असाइनमेंट जमा करने से पहले यह सुनिश्चित करता/करती हूँ कि उसमें कोई गलती न हो।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-07",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_C",
    questionText: "I set clear weekly goals and track my syllabus coverage methodically.",
    questionTextHi: "मैं स्पष्ट साप्ताहिक लक्ष्य तय करता/करती हूँ और अपने पाठ्यक्रम की प्रगति ट्रैक करता/करती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-08",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_C",
    questionText: "I am reliable and always keep my commitments to group projects and study sessions.",
    questionTextHi: "मैं हमेशा अपनी प्रतिबद्धताओं और वादों को पूरी ईमानदारी से पूरा करता/करती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-09",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_E",
    questionText: "I feel energized when participating in group discussions, seminars, and school events.",
    questionTextHi: "समूह चर्चा, सेमिनार और स्कूल के कार्यक्रमों में भाग लेने से मुझमें नई ऊर्जा आती है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-10",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_E",
    questionText: "I am comfortable starting conversations with new people and making friends quickly.",
    questionTextHi: "मैं नए लोगों से बातचीत शुरू करने और दोस्त बनाने में बहुत सहज रहता/रहती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-11",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_E",
    questionText: "I express my opinions confidently in front of large audiences and classrooms.",
    questionTextHi: "मैं कक्षा या बड़े मंच पर अपने विचार आत्मविश्वास के साथ प्रस्तुत कर सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-12",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_E",
    questionText: "I prefer lively, interactive study sessions over isolated quiet rooms.",
    questionTextHi: "मुझे अकेले शांत कमरे के बजाय जीवंत और संवादात्मक अध्ययन सत्र पसंद हैं।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-13",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_A",
    questionText: "I genuinely care about the well-being of others and listen to their concerns patiently.",
    questionTextHi: "मैं दूसरों की भलाई की परवाह करता/करती हूँ और उनकी बातों को धैर्यपूर्वक सुनता/सुनती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-14",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_A",
    questionText: "I prefer cooperative solutions where everyone benefits rather than intense rivalries.",
    questionTextHi: "मैं टकराव के बजाय ऐसे समाधान तलाशता/तलाशती हूँ जिससे सबका हित हो।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-15",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_A",
    questionText: "I am quick to forgive mistakes and believe the best in my peers.",
    questionTextHi: "मैं दूसरों की गलतियों को जल्दी क्षमा कर देता/देती हूँ और सकारात्मक दृष्टिकोण रखता/रखती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-16",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_A",
    questionText: "I am sensitive to the needs of teammates and actively support struggling peers.",
    questionTextHi: "मैं साथियों की जरूरतों को समझकर उनकी मदद के लिए हमेशा तत्पर रहता/रहती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-17",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_N",
    questionText: "I remain composed, calm, and level-headed during high-stakes exams and timed tests.",
    questionTextHi: "कठिन और महत्वपूर्ण परीक्षाओं के दौरान मैं शांत और संतुलित रहता/रहती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-18",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_N",
    questionText: "I rarely get overwhelmed by unexpected schedule changes or difficult questions.",
    questionTextHi: "अचानक आए बदलावों या कठिन प्रश्नों से मैं आसानी से विचलित नहीं होता/होती।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-19",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_N",
    questionText: "I maintain steady confidence and self-belief even when peers are stressing out.",
    questionTextHi: "जब अन्य लोग तनाव में होते हैं, तब भी मैं अपने आत्मविश्वास और फोकस को बनाए रखता/रखती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "oce-20",
    tier: "tier3_ocean",
    submodule: "ocean_personality",
    submoduleTitle: "Big Five Personality Dynamics",
    submoduleTitleHi: "बिग फाइव व्यक्तित्व विश्लेषण",
    traitCode: "OCEAN_N",
    questionText: "I manage frustration constructively and channel pressure into laser-sharp focus.",
    questionTextHi: "मैं निराशा को सकारात्मक ऊर्जा में बदलकर अपने लक्ष्य पर पूरा ध्यान केंद्रित करता/करती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },

  // ===================== TIER 4: MENTAL HEALTH & RESILIENCE (12 Questions) =====================
  {
    id: "str-01",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_ANXIETY",
    questionText: "I often feel physical tension or nervous racing thoughts the night before an exam.",
    questionTextHi: "परीक्षा से पहले की रात मुझे अक्सर बेचैनी या घबराहट महसूस होती है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-02",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_ANXIETY",
    questionText: "I worry excessively about failing or falling short of family expectations.",
    questionTextHi: "मैं कभी-कभी परिवार की अपेक्षाओं पर खरा न उतर पाने की अत्यधिक चिंता करने लगता/लगती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-03",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_ANXIETY",
    questionText: "During exams, seeing other students write fast makes me anxious about my pace.",
    questionTextHi: "परीक्षा हॉल में दूसरों को तेज़ी से लिखते देखकर मुझे अपनी गति को लेकर तनाव होने लगता है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-04",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_ANXIETY",
    questionText: "I find it hard to disconnect my mind from syllabus worries during sleep or breaks.",
    questionTextHi: "पढ़ाई के ब्रेक या सोने के समय भी मेरे दिमाग से परीक्षा की चिंताएं आसानी से नहीं निकलतीं।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-05",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_SELF_EFFICACY",
    questionText: "I am confident that with dedicated effort and strategy, I can master the toughest subjects.",
    questionTextHi: "मुझे विश्वास है कि योजनाबद्ध प्रयास से मैं सबसे कठिन विषय में भी महारत हासिल कर सकता/सकती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-06",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_SELF_EFFICACY",
    questionText: "When I encounter a difficult concept, I break it down into smaller manageable parts.",
    questionTextHi: "जब कोई जटिल सिद्धांत समझ नहीं आता, तो मैं उसे छोटे-छोटे हिस्सों में बांटकर समझता/समझती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-07",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_SELF_EFFICACY",
    questionText: "I trust my memory and preparation when entering the examination hall.",
    questionTextHi: "परीक्षा हॉल में जाते समय मुझे अपनी तैयारी और याददाश्त पर पूरा भरोसा होता है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-08",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_SELF_EFFICACY",
    questionText: "I can devise my own revision strategies that match my personal learning speed.",
    questionTextHi: "मैं अपनी गति के अनुसार स्वयं प्रभावी रिवीजन रणनीति बनाने में पूरी तरह सक्षम हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-09",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_RESILIENCE",
    questionText: "When I get low marks in a test, I analyze my mistakes immediately and bounce back stronger.",
    questionTextHi: "जब मुझे किसी टेस्ट में कम अंक मिलते हैं, तो मैं तुरंत गलतियों का विश्लेषण करके अधिक मजबूती से आगे बढ़ता/बढ़ती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-10",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_RESILIENCE",
    questionText: "I view mock test mistakes as valuable data points rather than personal failures.",
    questionTextHi: "मैं मॉक टेस्ट की गलतियों को विफलता नहीं बल्कि सीखने का सुनहरा अवसर मानता/मानती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-11",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_RESILIENCE",
    questionText: "I can reset my mental state within minutes after an upsetting mock score.",
    questionTextHi: "खराब परिणाम आने के बाद भी मैं कुछ ही मिनटों में अपना मानसिक संतुलन पुनः स्थापित कर लेता/लेती हूँ।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
  {
    id: "str-12",
    tier: "mental_health",
    submodule: "stress_resilience",
    submoduleTitle: "Exam Stress & Resilience Metric",
    submoduleTitleHi: "परीक्षा तनाव एवं रेज़िलिएंस मापन",
    traitCode: "ENABLER_RESILIENCE",
    questionText: "I believe my potential is not defined by any single exam score or ranking.",
    questionTextHi: "मेरा दृढ़ विश्वास है कि मेरी वास्तविक क्षमता किसी एक परीक्षा के अंक या रैंक तक सीमित नहीं है।",
    type: "likert_5",
    options: [{"id": "1", "text": "Strongly Disagree", "textHi": "पूरी तरह असहमत"}, {"id": "2", "text": "Disagree", "textHi": "असहमत"}, {"id": "3", "text": "Neutral / Unsure", "textHi": "तटस्थ / अनिश्चित"}, {"id": "4", "text": "Agree", "textHi": "सहमत"}, {"id": "5", "text": "Strongly Agree", "textHi": "पूरी तरह सहमत"}],
  },
];

const DISHA_TIER_CONFIG = {
  tier1_riasec: {
    id: "tier1_riasec",
    name: "Tier 1: Comprehensive Holland RIASEC Battery",
    nameHi: "टियर 1 (विस्तृत): हॉलैंड आरआईएएसईसी रुचि इन्वेंट्री (42 प्रश्न)",
    icon: "🎯",
    badge: "Gold Standard Assessment",
    badgeHi: "स्वर्ण मानक मूल्यांकन (42 प्रश्न)",
    color: "#c9432a",
    duration: "10-12 mins",
    totalQuestions: 42,
    description: "42 standardized vocational interest items (7 per domain) giving you the highest precision Holland Code across Realistic, Investigative, Artistic, Social, Enterprising, and Conventional careers.",
    descriptionHi: "42 प्रामाणिक प्रश्नों (प्रत्येक क्षेत्र में 7 प्रश्न) द्वारा अपने करियर रुझानों का सबसे सटीक व गहरा वैज्ञानिक विश्लेषण प्राप्त करें।",
  },
  tier1_quick_riasec: {
    id: "tier1_quick_riasec",
    name: "Tier 1 (Fast-Track): Quick RIASEC Career Pulse",
    nameHi: "टियर 1 (फास्ट-ट्रैक): त्वरित करियर पल्स (24 प्रश्न)",
    icon: "⚡",
    badge: "5-Min Quick Discovery",
    badgeHi: "5 मिनट त्वरित खोज (24 प्रश्न)",
    color: "#f59e0b",
    duration: "4-5 mins",
    totalQuestions: 24,
    description: "24 rapid situational items (4 per domain) designed for students seeking quick, high-speed initial career interest orientation.",
    descriptionHi: "24 त्वरित व्यावहारिक प्रश्नों द्वारा मात्र 5 मिनट में अपनी मुख्य रुचियों और प्राथमिक करियर दिशा का तुरंत पता लगाएं।",
  },
  tier2_tamanna: {
    id: "tier2_tamanna",
    name: "Tier 2: NCERT TAMANNA Aptitude Battery",
    nameHi: "टियर 2: NCERT तमन्ना योग्यता बैटरी (28 प्रश्न)",
    icon: "🧠",
    badge: "Cognitive Benchmark",
    badgeHi: "संज्ञानात्मक योग्यता (28 प्रश्न)",
    color: "#2563eb",
    duration: "15-18 mins",
    totalQuestions: 28,
    description: "Evaluate your cognitive strengths across 7 NCERT & CBSE standardized aptitude dimensions (Language, Spatial, Numerical, Mechanical, Reasoning).",
    descriptionHi: "NCERT और CBSE द्वारा प्रमाणित 7 प्रमुख संज्ञानात्मक योग्यताओं (भाषा, संख्यात्मक, स्थानिक, यांत्रिक, तार्किक) का मूल्यांकन करें।",
  },
  tier3_ocean: {
    id: "tier3_ocean",
    name: "Tier 3: Big Five (OCEAN) Personality",
    nameHi: "टियर 3: बिग फाइव (OCEAN) व्यक्तित्व (20 प्रश्न)",
    icon: "🌟",
    badge: "Behavioral Blueprint",
    badgeHi: "व्यवहारिक खाका (20 प्रश्न)",
    color: "#8b5cf6",
    duration: "8-10 mins",
    totalQuestions: 20,
    description: "Deep dive into your Openness, Conscientiousness, Extraversion, Agreeableness, and Emotional Stability in study and teamwork.",
    descriptionHi: "अपने व्यक्तित्व के 5 मुख्य पहलुओं (अनुशासन, मिलनसारिता, जिज्ञासा, सहयोग, तनाव नियंत्रण) का विश्लेषण करें।",
  },
  mental_health: {
    id: "mental_health",
    name: "Tier 4: Exam Stress & Resilience Index",
    nameHi: "टियर 4: परीक्षा तनाव व लचीलापन सूचकांक (12 प्रश्न)",
    icon: "🧘",
    badge: "Well-being Index",
    badgeHi: "कल्याण सूचकांक (12 प्रश्न)",
    color: "#10b981",
    duration: "5-7 mins",
    totalQuestions: 12,
    description: "Understand academic anxiety, study self-efficacy, and develop emotional coping mechanisms and setback resilience.",
    descriptionHi: "परीक्षा से जुड़े तनाव का आकलन करें और कठिन समय में सकारात्मक रहने की तकनीकें सीखें।",
  },
};

window.DISHA_ASSESSMENT_TRAITS = DISHA_ASSESSMENT_TRAITS;
window.DISHA_ALL_QUESTIONS = DISHA_ALL_QUESTIONS;
window.DISHA_TIER_CONFIG = DISHA_TIER_CONFIG;
