/* Phase 1 Discovery data — RIASEC, Aptitude, Careers */
window.DISHA_DATA = {
  educationLevels: [
    { id: "class_6", grade: "6", label: "Class 6th", hi: "कक्षा 6वीं", group: "group_1", stage: "Discovery Stage", stageHi: "डिस्कवरी स्टेज (कक्षा 6–8)", type: "school" },
    { id: "class_7", grade: "7", label: "Class 7th", hi: "कक्षा 7वीं", group: "group_1", stage: "Discovery Stage", stageHi: "डिस्कवरी स्टेज (कक्षा 6–8)", type: "school" },
    { id: "class_8", grade: "8", label: "Class 8th", hi: "कक्षा 8वीं", group: "group_1", stage: "Discovery Stage", stageHi: "डिस्कवरी स्टेज (कक्षा 6–8)", type: "school" },
    { id: "class_9", grade: "9", label: "Class 9th", hi: "कक्षा 9वीं", group: "group_2", stage: "Exploration Stage", stageHi: "एक्सप्लोरेशन स्टेज (कक्षा 9–10)", type: "school" },
    { id: "class_10", grade: "10", label: "Class 10th (Stream Choice)", hi: "कक्षा 10वीं (स्ट्रीम चयन)", group: "group_2", stage: "Exploration Stage", stageHi: "एक्सप्लोरेशन स्टेज (कक्षा 9–10)", type: "school" },
    { id: "class_11", grade: "11", label: "Class 11th", hi: "कक्षा 11वीं", group: "group_3", stage: "Decision Stage", stageHi: "डिसीजन स्टेज (कक्षा 11–12)", type: "school" },
    { id: "class_12", grade: "12", label: "Class 12th (College & Career)", hi: "कक्षा 12वीं (कॉलेज एवं करियर)", group: "group_3", stage: "Decision Stage", stageHi: "डिसीजन स्टेज (कक्षा 11–12)", type: "school" },
  ],

  frameworkTiers: {
    tier1_riasec: {
      id: "tier1_riasec",
      title: "Find Your Interests (RIASEC)",
      titleHi: "रुचि खोज (RIASEC)",
      tool: "RIASEC Inventory",
      toolHi: "RIASEC इन्वेंटरी",
      badge: "6 Interest Types · 42 Questions",
      badgeHi: "6 रुचि क्षेत्र · 42 प्रश्न",
      desc: "Identifies your natural inclinations across 6 interest types to match career paths.",
      descHi: "6 व्यापक रुचि प्रकारों की पहचान कर उन्हें करियर क्लस्टरों से जोड़ता है।",
      qCount: 42,
      icon: "🎯",
      reportTitle: "Level 1 - Interest Inventory Report",
      reportTitleHi: "लेवल 1 - रुचि इन्वेंटरी रिपोर्ट"
    },
    tier2_tamanna: {
      id: "tier2_tamanna",
      title: "Discover Your Aptitudes (NCERT TAMANNA)",
      titleHi: "अभिक्षमता खोज [NCERT TAMANNA]",
      tool: "TAMANNA (NCERT)",
      toolHi: "तमन्ना (NCERT)",
      badge: "7 Cognitive Domains · 28 Questions",
      badgeHi: "7 संज्ञानात्मक आयाम · 28 प्रश्न",
      desc: "Evaluates 7 core cognitive abilities essential for stream and course selection.",
      descHi: "स्ट्रीम और करियर चयन हेतु आवश्यक 7 प्रमुख संज्ञानात्मक क्षमताओं का मूल्यांकन करता है।",
      qCount: 28,
      icon: "🧠",
      reportTitle: "Level 2 - Aptitude Test Report",
      reportTitleHi: "लेवल 2 - अभिक्षमता परीक्षण रिपोर्ट"
    },
    tier3_ocean: {
      id: "tier3_ocean",
      title: "Understand Your Personality (Big Five OCEAN)",
      titleHi: "व्यक्तित्व समझ [Big Five OCEAN]",
      tool: "The Big Five (OCEAN)",
      toolHi: "द बिग फाइव (OCEAN)",
      badge: "5 Personality Dimensions · 20 Questions",
      badgeHi: "5 व्यक्तित्व आयाम · 20 प्रश्न",
      desc: "Evaluates core behavioral traits supporting higher education and professional tracks.",
      descHi: "उच्च शिक्षा और पेशेवर करियर में अनुकूलता के लिए 5 मुख्य व्यक्तित्व आयामों का समग्र मूल्यांकन करता है।",
      qCount: 20,
      icon: "🌟",
      reportTitle: "Level 3 - Personality Assessment Report",
      reportTitleHi: "लेवल 3 - व्यक्तित्व परीक्षण रिपोर्ट"
    }
  },

  studentGroups: {
    group_1: {
      id: "group_1",
      groupNo: "Group I",
      classesLabel: "Classes 6–8",
      classesLabelHi: "कक्षा 6–8",
      classes: ["6", "7", "8"],
      stage: "Discovery Stage",
      stageHi: "डिस्कवरी स्टेज (खोज स्तर)",
      badgeIcon: "🌱",
      stageColor: "var(--marigold)",
      stageBg: "rgba(224, 159, 62, 0.16)",
      assessmentTitle: "Find Your Interests",
      assessmentTitleHi: "रुचि खोज (Find Your Interests)",
      focus: "Explores natural inclinations across 6 broad interest types without pushing toward premature career decisions.",
      focusHi: "बिना किसी जल्दबाजी के 6 व्यापक रुचि प्रकारों की खोज कर शुरुआती पसंद-नापसंद को समझें।",
      requiredAssessments: ["tier1_riasec"],
      reportTitle: "Level 1 - Interest Inventory Report",
      reportTitleHi: "लेवल 1 - रुचि इन्वेंटरी रिपोर्ट"
    },
    group_2: {
      id: "group_2",
      groupNo: "Group II",
      classesLabel: "Classes 9–10",
      classesLabelHi: "कक्षा 9–10",
      classes: ["9", "10"],
      stage: "Exploration Stage",
      stageHi: "एक्सप्लोरेशन स्टेज (अन्वेषण स्तर)",
      badgeIcon: "🧭",
      stageColor: "var(--teal)",
      stageBg: "rgba(45, 212, 191, 0.16)",
      assessmentTitle: "Find Your Interests + Discover Your Aptitudes",
      assessmentTitleHi: "रुचि खोज + अभिक्षमता खोज",
      focus: "Combines interests with cognitive strengths to scientifically guide 11th–12th stream selection.",
      focusHi: "कक्षा 11-12 में सही स्ट्रीम (साइंस, कॉमर्स, आर्ट्स) चयन के लिए रुचि और वास्तविक संज्ञानात्मक क्षमताओं का संयुक्त मूल्यांकन।",
      requiredAssessments: ["tier1_riasec", "tier2_tamanna"],
      reportTitle: "Level 1 (Interest) + Level 2 (Aptitude & Stream) Report",
      reportTitleHi: "लेवल 1 (रुचि) + लेवल 2 (अभिक्षमता एवं स्ट्रीम चयन) रिपोर्ट"
    },
    group_3: {
      id: "group_3",
      groupNo: "Group III",
      classesLabel: "Classes 11–12",
      classesLabelHi: "कक्षा 11–12",
      classes: ["11", "12"],
      stage: "Decision / Refinement Stage",
      stageHi: "डिसीजन स्टेज (निर्णय एवं परिष्कार स्तर)",
      badgeIcon: "🎯",
      stageColor: "var(--vermilion)",
      stageBg: "rgba(201, 67, 42, 0.14)",
      assessmentTitle: "Find Your Interests + Discover Your Aptitudes + Understand Your Personality",
      assessmentTitleHi: "रुचि खोज + अभिक्षमता खोज + व्यक्तित्व समझ",
      focus: "Three-pronged developmental assessment supporting well-rounded higher education and career choices.",
      focusHi: "कॉलेज, डिग्री कोर्स एवं करियर चयन हेतु रुचि, अभिक्षमता और व्यक्तित्व का त्रि-आयामी संपूर्ण मूल्यांकन।",
      requiredAssessments: ["tier1_riasec", "tier2_tamanna", "tier3_ocean"],
      reportTitle: "Level 1 (Interest) + Level 2 (Personality) + Level 3 (Aptitude) Report",
      reportTitleHi: "लेवल 1 (रुचि) + लेवल 2 (व्यक्तित्व) + लेवल 3 (अभिक्षमता) त्रि-आयामी रिपोर्ट"
    }
  },

  streams: [
    { id: "general", label: "General / Foundational (All Subjects)", hi: "सामान्य / सभी बुनियादी विषय" },
    { id: "science_pcm", label: "Science (PCM - Physics, Chemistry, Maths)", hi: "विज्ञान (PCM - भौतिक, रसायन, गणित)" },
    { id: "science_pcb", label: "Science (PCB - Physics, Chemistry, Biology)", hi: "विज्ञान (PCB - भौतिक, रसायन, जीव विज्ञान)" },
    { id: "science_pcmb", label: "Science (PCMB - Maths + Biology)", hi: "विज्ञान (PCMB - गणित + जीव विज्ञान)" },
    { id: "commerce", label: "Commerce (Accounts, Economics, Business)", hi: "वाणिज्य / कॉमर्स (लेखा, अर्थशास्त्र, व्यवसाय)" },
    { id: "humanities", label: "Humanities / Arts (History, Pol Sci, Psych)", hi: "मानविकी / कला (इतिहास, राजनीति, मनोविज्ञान)" },
    { id: "eng_tech", label: "Engineering & Tech (CS, AI, IT, Mechanical, etc.)", hi: "इंजीनियरिंग एवं तकनीक (CS, AI, IT आदि)" },
    { id: "med_health", label: "Medical & Health (MBBS, BDS, Pharma, Nursing)", hi: "चिकित्सा व स्वास्थ्य सेवा (MBBS, नर्सिंग आदि)" },
    { id: "management", label: "Business, Management & Finance (BBA, MBA)", hi: "बिजनेस एवं मैनेजमेंट (BBA, MBA, B.Com)" },
    { id: "law", label: "Law & Legal Studies (BA LLB, LLM)", hi: "विधि / कानून (Law - LLB)" },
    { id: "design_media", label: "Design, Fine Arts, Animation & Film", hi: "डिज़ाइन, एनिमेशन, फाइन आर्ट्स एवं मीडिया" },
    { id: "other", label: "Other / Multidisciplinary", hi: "अन्य / बहु-विषयक" },
  ],

  roleModelArchetypes: [
    {
      id: "tech",
      title: "Tech Innovator & AI Visionary",
      hiTitle: "तकनीक एवं एआई नवप्रवर्तक",
      icon: "💻",
      idols: "Sundar Pichai, Sam Altman, Elon Musk, Linus Torvalds, Ada Lovelace",
      hiIdols: "सुंदर पिचाई, सैम ऑल्टमैन, एलोन मस्क, एडा लवलेस",
      defaultReason: "Building game-changing AI, software & products that empower billions",
      hiReason: "दुनिया को बदलने वाले एआई, सॉफ्टवेयर और ऐप्स का निर्माण करना",
      quote: "I want to invent cutting-edge technology, build intelligent software, and solve complex digital challenges.",
      hiQuote: "मैं आधुनिक तकनीक और एआई बनाकर वैश्विक समस्याओं को हल करना चाहता/चाहती हूँ।",
      impactPills: ["AI & Apps", "Coding & Systems", "Silicon Valley & Tech Giants"],
    },
    {
      id: "healer",
      title: "Doctor, Healer & Life Saver",
      hiTitle: "चिकित्सक एवं जीवन रक्षक (Doctor/Healer)",
      icon: "🩺",
      idols: "Dr. Devi Shetty, Dr. APJ Abdul Kalam, Florence Nightingale, Dr. Soumya Swaminathan",
      hiIdols: "डॉ. देवी शेट्टी, डॉ. एपीजे अब्दुल कलाम, फ्लोरेंस नाइटिंगेल",
      defaultReason: "Saving human lives, diagnosing critical diseases, and delivering compassionate care",
      hiReason: "मरीजों का इलाज करना, जीवन बचाना और हर वर्ग तक स्वास्थ्य सेवा पहुँचाना",
      quote: "I want to cure diseases, perform surgeries, and bring affordable world-class healthcare to all.",
      hiQuote: "मैं रोगियों का इलाज करके लोगों का जीवन बचाना और स्वास्थ्य सेवा में योगदान देना चाहता/चाहती हूँ।",
      impactPills: ["Saving Lives", "Medical Breakthroughs", "Community Health"],
    },
    {
      id: "entrepreneur",
      title: "Startup Founder & Business Leader",
      hiTitle: "स्टार्टअप संस्थापक एवं बिजनेस लीडर",
      icon: "🚀",
      idols: "Ratan Tata, Steve Jobs, Ghazal Alagh, N.R. Narayana Murthy, Deepinder Goyal",
      hiIdols: "रतन टाटा, स्टीव जॉब्स, ग़ज़ल अलघ, नारायण मूर्ति, दीपिंदर गोयल",
      defaultReason: "Starting innovative companies, creating thousands of jobs, and solving real-world needs",
      hiReason: "नया स्टार्टअप खड़ा करना, नौकरियां पैदा करना और भारत का नाम विश्व में चमकाना",
      quote: "I want to build an iconic startup, scale impactful products, and become a visionary entrepreneur.",
      hiQuote: "मैं अपना बिजनेस खड़ा करना, नए अवसर बनाना और एक सफल उद्यमी बनना चाहता/चाहती हूँ।",
      impactPills: ["Job Creation", "Startup Disruption", "Venture Growth"],
    },
    {
      id: "athlete",
      title: "Champion Athlete & Sports Icon",
      hiTitle: "चैंपियन एथलीट एवं खेल सितारा",
      icon: "🏆",
      idols: "Virat Kohli, Neeraj Chopra, PV Sindhu, Cristiano Ronaldo, Mary Kom",
      hiIdols: "विराट कोहली, नीरज चोपड़ा, पीवी सिंधु, मैरी कॉम, रोनाल्डो",
      defaultReason: "Pushing human physical limits, winning international gold medals, and bringing national pride",
      hiReason: "कड़ी मेहनत से तिरंगा लहराना और दुनिया भर के टूर्नामेंट्स में देश का नाम रोशन करना",
      quote: "I want to excel at the highest level of sports, train with unwavering discipline, and inspire youth.",
      hiQuote: "मैं खेल के मैदान पर सर्वश्रेष्ठ प्रदर्शन करके देश के लिए मेडल जीतना चाहता/चाहती हूँ।",
      impactPills: ["National Pride", "Olympic/World Glory", "Elite Fitness"],
    },
    {
      id: "gamer",
      title: "Esports Pro, Streamer & Gamer",
      hiTitle: "ई-स्पोर्ट्स प्रो गेमर एवं स्ट्रीमर",
      icon: "🎮",
      idols: "Mortal (Naman Mathur), Scout (Tanmay Singh), Faker, Shroud, Jonathan Gaming",
      hiIdols: "मोर्टल (नमन माथुर), स्काउट, जोनाथन, फेकर, निंजा",
      defaultReason: "Competing in global esports championships and entertaining millions with gaming content",
      hiReason: "इंटरनेशनल ई-स्पोर्ट्स टूर्नामेंट जीतना और एक विशाल गेमिंग कम्युनिटी बनाना",
      quote: "I want to master esports tactical gameplay, lead a championship gaming roster, and stream to millions.",
      hiQuote: "मैं पेशेवर ई-स्पोर्ट्स में शीर्ष स्थान हासिल करना और गेमिंग की दुनिया में नाम कमाना चाहता/चाहती हूँ।",
      impactPills: ["Competitive Gaming", "Esports Arenas", "Streaming & Content"],
    },
    {
      id: "artist",
      title: "Creative Artist, Musician & Designer",
      hiTitle: "रचनात्मक कलाकार, संगीतकार व डिज़ाइनर",
      icon: "🎨",
      idols: "A.R. Rahman, Satyajit Ray, Hayao Miyazaki, Zaha Hadid, Raja Ravi Varma",
      hiIdols: "ए.आर. रहमान, सत्यजीत रे, हयाओ मियाज़ाकी, ज़ाहा हदीद",
      defaultReason: "Composing moving music, crafting visual masterpieces, and telling mesmerizing stories",
      hiReason: "दिल को छूने वाला संगीत, शानदार कला और सिनेमा रचना",
      quote: "I want to express profound emotions through visual art, soul-stirring music, design, and storytelling.",
      hiQuote: "मैं अपनी कला, संगीत और डिज़ाइन के ज़रिए लोगों के दिलों को छूना चाहता/चाहती हूँ।",
      impactPills: ["Music & Soundtracks", "Visual Art & Design", "Cinematic Stories"],
    },
    {
      id: "creator",
      title: "Digital Creator & Influencer",
      hiTitle: "डिजिटल कंटेंट क्रिएटर एवं इन्फ्लुएंसर",
      icon: "🎥",
      idols: "Tanmay Bhat, Marques Brownlee (MKBHD), Prajakta Koli, Dhruv Rathee, MrBeast",
      hiIdols: "तन्मय भट्ट, एमकेबीएचडी, प्राजक्ता कोली, मिस्टर बीस्ट",
      defaultReason: "Engaging millions through entertaining videos, honest reviews, and thought-provoking discussions",
      hiReason: "यूट्यूब और डिजिटल मीडिया के ज़रिए ज्ञान, मनोरंजन और प्रेरणा देना",
      quote: "I want to produce viral, high-value digital content that entertains, educates, and empowers the audience.",
      hiQuote: "मैं उच्च गुणवत्ता वाला कंटेंट बनाकर लाखों लोगों को शिक्षित और प्रेरित करना चाहता/चाहती हूँ।",
      impactPills: ["YouTube & Podcasts", "Viral Storytelling", "Audience Connection"],
    },
    {
      id: "civil_service",
      title: "Nation Builder & Civil Servant (IAS/IPS/Diplomat)",
      hiTitle: "राष्ट्र निर्माता एवं लोक सेवक (IAS/IPS/Diplomat)",
      icon: "🏛️",
      idols: "Dr. B.R. Ambedkar, Kiran Bedi, S. Jaishankar, Sardar Vallabhbhai Patel",
      hiIdols: "डॉ. बी.आर. अम्बेडकर, किरण बेदी, एस. जयशंकर, सरदार वल्लभभाई पटेल",
      defaultReason: "Implementing grassroots development, upholding the constitution, and serving the motherland",
      hiReason: "ईमानदार प्रशासन, जन कल्याण की नीतियां और देश की प्रगति में सक्रिय भूमिका",
      quote: "I want to crack civil services, serve the underprivileged, enforce good governance, and uplift society.",
      hiQuote: "मैं प्रशासनिक सेवा में जाकर समाज के अंतिम व्यक्ति तक न्याय और विकास पहुँचाना चाहता/चाहती हूँ।",
      impactPills: ["Civil Services / UPSC", "Public Policy", "Social Justice"],
    },
    {
      id: "scientist",
      title: "Scientist & Space Explorer",
      hiTitle: "वैज्ञानिक एवं अंतरिक्ष अन्वेषक (ISRO/NASA)",
      icon: "🔬",
      idols: "C.V. Raman, Kalpana Chawla, Marie Curie, Homi Bhabha, Vikram Sarabhai",
      hiIdols: "सी.वी. रमन, कल्पना चावला, मैरी क्यूरी, विक्रम साराभाई",
      defaultReason: "Exploring cosmic mysteries, developing rockets, and pioneering scientific discoveries",
      hiReason: "ब्रह्मांड के रहस्य खोजना, रॉकेट तकनीक विकसित करना और नए वैज्ञानिक शोध करना",
      quote: "I want to conduct breakthrough scientific experiments, explore deep space, and discover new laws of nature.",
      hiQuote: "मैं वैज्ञानिक शोध और अंतरिक्ष अभियानों के ज़रिए मानव ज्ञान को एक नए मुकाम पर ले जाना चाहता/चाहती हूँ।",
      impactPills: ["ISRO & NASA Missions", "Fundamental Physics/Bio", "Inventions"],
    },
    {
      id: "custom",
      title: "My Unique Inspiration / Custom Idol",
      hiTitle: "मेरा अपना विशिष्ट आदर्श / मेरा अपना सपना",
      icon: "⭐",
      idols: "My Parents, Teachers, Local Community Hero, or Self-Drive",
      hiIdols: "मेरे माता-पिता, गुरुजन, कोई स्थानीय नायक, या मेरी अपनी लगन",
      defaultReason: "Blazing an authentic, unique path tailored to my personal passions",
      hiReason: "अपनी शर्तों पर एक अलग और प्रेरणादायक पहचान बनाना",
      quote: "I want to build my own unique journey and leave a lasting positive mark on the world.",
      hiQuote: "मैं अपनी मेहनत और लगन से अपनी खुद की एक अलग पहचान बनाना चाहता/चाहती हूँ।",
      impactPills: ["Custom Path", "Personal Vision", "Unstoppable Drive"],
    },
  ],

  workStyles: [
    { id: "hands_on", label: "Practical & Hands-on Builder", hi: "प्रैक्टिकल व हाथों से निर्माण", icon: "🛠️", desc: "Learning by doing, experimenting with tools and building real models.", hiDesc: "करके सीखना, औज़ारों के साथ प्रयोग और मॉडल बनाना।" },
    { id: "analytical", label: "Deep Thinker & Problem Solver", hi: "गहन विश्लेषक व तार्किक समाधान", icon: "🧠", desc: "Analyzing numbers, logic puzzles, coding challenges and deep research.", hiDesc: "संख्याओं का विश्लेषण, तार्किक पहेलियाँ और कोडिंग।" },
    { id: "creative", label: "Creative, Visual & Expressive", hi: "रचनात्मक, कलात्मक व अभिव्यक्ति", icon: "🎨", desc: "Visualizing aesthetics, storytelling, designing and emotional depth.", hiDesc: "सौंदर्यशास्त्र, कहानी सुनाना, डिज़ाइन और रचनात्मकता।" },
    { id: "collaborative", label: "Team Leader & People Person", hi: "टीम लीडर व मिलनसार मार्गदर्शक", icon: "👥", desc: "Inspiring teams, organizing events, debating and driving group energy.", hiDesc: "टीम का मार्गदर्शन, आयोजन, वाद-विवाद और सामाजिक ऊर्जा।" },
    { id: "independent", label: "Self-Driven & Deep Focus", hi: "शांत व स्वतंत्र अध्ययनकर्ता", icon: "📖", desc: "Working in calm flow states with total autonomy and focused depth.", hiDesc: "शांत वातावरण में स्वायत्तता और गहन ध्यान से काम करना।" },
  ],

  interestCategories: [
    { id: "all", label: "✨ All Interests", hi: "✨ सभी रुचियां" },
    { id: "sports", label: "⚽ Sports & Athletics", hi: "⚽ खेलकूद" },
    { id: "esports", label: "🎮 Esports & Gaming", hi: "🎮 ई-स्पोर्ट्स व गेमिंग" },
    { id: "creative", label: "🎨 Creative Arts & Media", hi: "🎨 कला व मीडिया" },
    { id: "tech", label: "💻 Tech & Coding", hi: "💻 तकनीक व कोडिंग" },
    { id: "science", label: "🔬 Science & Medicine", hi: "🔬 विज्ञान व चिकित्सा" },
    { id: "business", label: "📈 Business & Finance", hi: "📈 बिजनेस व वित्त" },
    { id: "public", label: "🏛️ Public Service & Law", hi: "🏛️ लोक सेवा व कानून" },
    { id: "hands_on", label: "🛠️ Hands-on & Making", hi: "🛠️ शिल्प व निर्माण" },
  ],

  interests: [
    // Sports & Athletics
    { id: "cricket", category: "sports", label: "Cricket", hi: "क्रिकेट", icon: "🏏" },
    { id: "football", category: "sports", label: "Football", hi: "फ़ुटबॉल", icon: "⚽" },
    { id: "badminton", category: "sports", label: "Badminton & Racket Sports", hi: "बैडमिंटन व टेनिस", icon: "🏸" },
    { id: "athletics_fitness", category: "sports", label: "Athletics, Gym & Martial Arts", hi: "एथलेटिक्स, जिम व मार्शल आर्ट्स", icon: "🥋" },
    { id: "chess_strategy", category: "sports", label: "Chess & Mind Sports", hi: "शतरंज व माइंड स्पोर्ट्स", icon: "♟️" },

    // Esports & Gaming
    { id: "esports_comp", category: "esports", label: "Competitive Esports (BGMI / Valorant / CS)", hi: "प्रतियोगी ई-स्पोर्ट्स गेमिंग", icon: "🎮" },
    { id: "game_streaming", category: "esports", label: "Game Streaming & Shoutcasting", hi: "गेम स्ट्रीमिंग व कमेंट्री", icon: "🎙️" },
    { id: "game_design", category: "esports", label: "Game Design & Level Creation", hi: "गेम डिज़ाइन व स्टोरीबोर्डिंग", icon: "🕹️" },

    // Creative Arts & Media
    { id: "arts", category: "creative", label: "Fine Arts, Painting & Sketching", hi: "ललित कला व रेखाचित्र", icon: "🎨" },
    { id: "music", category: "creative", label: "Music Production & Singing", hi: "संगीत निर्माण व गायन", icon: "🎵" },
    { id: "digital_art", category: "creative", label: "Digital Art, 3D & Animation", hi: "डिजिटल आर्ट, 3D व एनिमेशन", icon: "🖌️" },
    { id: "video_editing", category: "creative", label: "Video Editing & VFX", hi: "वीडियो एडिटिंग व वीएफएक्स", icon: "🎬" },
    { id: "photography", category: "creative", label: "Photography & Cinematography", hi: "फोटोग्राफी व सिनेमा", icon: "📸" },
    { id: "ui_ux", category: "creative", label: "UI/UX & Product Design", hi: "UI/UX व प्रोडक्ट डिज़ाइन", icon: "✨" },
    { id: "acting", category: "creative", label: "Acting, Theatre & Voice-over", hi: "अभिनय, थियेटर व वॉइस-ओवर", icon: "🎭" },
    { id: "creative_writing", category: "creative", label: "Creative Writing & Scriptwriting", hi: "रचनात्मक लेखन व पटकथा", icon: "✍️" },

    // Tech & Coding
    { id: "technology", category: "tech", label: "Software & Technology", hi: "तकनीक व सॉफ्टवेयर", icon: "💻" },
    { id: "ai_ml", category: "tech", label: "AI & Machine Learning", hi: "एआई व मशीन लर्निंग", icon: "🤖" },
    { id: "web_dev", category: "tech", label: "Web & Mobile App Development", hi: "वेब व मोबाइल ऐप डेवलपमेंट", icon: "📱" },
    { id: "cybersecurity", category: "tech", label: "Cybersecurity & Ethical Hacking", hi: "साइबर सुरक्षा व एथिकल हैकिंग", icon: "🛡️" },
    { id: "robotics", category: "tech", label: "Robotics & IoT Hardware", hi: "रोबोटिक्स व आईओटी", icon: "🦾" },

    // Science & Research
    { id: "healthcare", category: "science", label: "Healthcare & Medicine", hi: "चिकित्सा व स्वास्थ्य", icon: "🩺" },
    { id: "space", category: "science", label: "Space, Astronomy & Rockets", hi: "अंतरिक्ष, खगोल व रॉकेट", icon: "🚀" },
    { id: "psychology", category: "science", label: "Psychology & Human Behavior", hi: "मनोविज्ञान व व्यवहार", icon: "🧠" },
    { id: "biotech", category: "science", label: "Biotechnology & Genetics", hi: "बायोटेक्नोलॉजी व जेनेटिक्स", icon: "🧬" },
    { id: "environment", category: "science", label: "Ecology & Climate Tech", hi: "पर्यावरण व क्लाइमेट टेक", icon: "🌿" },
    { id: "agriculture", category: "science", label: "Modern Agriculture & AgriTech", hi: "आधुनिक कृषि व एग्रीटेक", icon: "🌾" },

    // Business & Finance
    { id: "business", category: "business", label: "Business & Startups", hi: "व्यवसाय व स्टार्टअप", icon: "📈" },
    { id: "stock_market", category: "business", label: "Stock Market, Investing & Fintech", hi: "शेयर बाज़ार, निवेश व फिनटेक", icon: "📊" },
    { id: "marketing", category: "business", label: "Digital Marketing & Branding", hi: "डिजिटल मार्केटिंग व ब्रांडिंग", icon: "📢" },
    { id: "e_commerce", category: "business", label: "E-Commerce & Online Stores", hi: "ई-कॉमर्स व ऑनलाइन व्यापार", icon: "📦" },

    // Public Impact, Law & Teaching
    { id: "public_service", category: "public", label: "Civil Services & Governance", hi: "सिविल सेवा व प्रशासन", icon: "🏛️" },
    { id: "defense", category: "public", label: "Defense & Armed Forces", hi: "रक्षा व सैन्य सेवा", icon: "🎖️" },
    { id: "law", category: "public", label: "Law, Judiciary & Human Rights", hi: "कानून, वकालत व न्यायपालिका", icon: "⚖️" },
    { id: "debate", category: "public", label: "Public Speaking & Debating", hi: "सार्वजनिक संभाषण व डिबेट", icon: "🎙️" },
    { id: "teaching", category: "public", label: "Teaching & Mentorship", hi: "शिक्षण व मेंटरशिप", icon: "🎓" },

    // Hands-on & Making
    { id: "architecture", category: "hands_on", label: "Architecture & Interior Design", hi: "वास्तुकla व इंटीरियर डिज़ाइन", icon: "🏛️" },
    { id: "automotive", category: "hands_on", label: "Automobiles & EV Technology", hi: "ऑटोमोबाइल व ईवी तकनीक", icon: "🏎️" },
    { id: "culinary", category: "hands_on", label: "Culinary Arts & MasterChef", hi: "पाक कला व शेफ", icon: "🍳" },
    { id: "fashion", category: "hands_on", label: "Fashion Design & Styling", hi: "फैशन डिज़ाइन व स्टाइलिंग", icon: "👗" },
  ],

  riasecMeta: {
    R: {
      name: "Realistic",
      hi: "व्यावहारिक",
      desc: "You like practical, hands-on tasks and working with tools.",
      hiDesc: "आपको हाथों से काम करना और औज़ार इस्तेमाल करना पसंद है।",
      tip: "working with your hands and tools",
      icon: "🔧",
    },
    I: {
      name: "Investigative",
      hi: "अनुसंधान",
      desc: "You enjoy exploring ideas, science, and solving puzzles.",
      hiDesc: "आप विचारों, विज्ञान और पहेलियाँ सुलझाने में रुचि रखते हैं।",
      tip: "analysing and discovering how things work",
      icon: "🔍",
    },
    A: {
      name: "Artistic",
      hi: "कलात्मक",
      desc: "You like creating, designing, and expressing ideas freely.",
      hiDesc: "आपको रचनात्मक काम और अपनी बात खुलकर व्यक्त करना पसंद है।",
      tip: "creative and expressive activities",
      icon: "🎨",
    },
    S: {
      name: "Social",
      hi: "सामाजिक",
      desc: "You enjoy helping others and working in teams.",
      hiDesc: "आपको दूसरों की मदद करना और टीम में काम करना पसंद है।",
      tip: "helping people and teaching",
      icon: "🤝",
    },
    E: {
      name: "Enterprising",
      hi: "उद्यमी",
      desc: "You like leading, persuading, and starting new things.",
      hiDesc: "आपको नेतृत्व करना, समझाना और नई शुरुआत करना पसंद है।",
      tip: "leading and persuading others",
      icon: "📣",
    },
    C: {
      name: "Conventional",
      hi: "व्यवस्थित",
      desc: "You like organising information, details, and clear systems.",
      hiDesc: "आपको जानकारी व्यवस्थित करना और स्पष्ट व्यवस्था पसंद है।",
      tip: "organising details and following systems",
      icon: "📋",
    },
  },

  /* 24 RIASEC items — Dislike / Not Sure / Like (0 / 1 / 2) */
  riasecQuestions: [
    { id: "r1", trait: "R", text: "I like to fix broken electrical things", hi: "मुझे बिजली की चीजें ठीक करना पसंद है", hint: "Think about fixing a fan, a switch, or a toy at home.", icon: "🔧" },
    { id: "r2", trait: "R", text: "I like building or repairing things with my hands", hi: "मुझे हाथों से चीजें बनाना या ठीक करना पसंद है", hint: "Like making a shelf, repairing a cycle, or craft work.", icon: "🛠️" },
    { id: "r3", trait: "R", text: "I enjoy outdoor physical work", hi: "मुझे बाहर शारीरिक काम करना अच्छा लगता है", hint: "Farming, sports practice, or helping with heavy tasks.", icon: "🌳" },
    { id: "r4", trait: "R", text: "I like working with machines or tools", hi: "मुझे मशीनों या औज़ारों से काम करना पसंद है", hint: "Kitchen tools, computers, pumps, or school lab equipment.", icon: "⚙️" },

    { id: "i1", trait: "I", text: "I like to do puzzles and brain teasers", hi: "मुझे पहेलियाँ और दिमागी खेल सुलझाना पसंद है", hint: "Riddles, logic games, or science questions.", icon: "🧩" },
    { id: "i2", trait: "I", text: "I enjoy learning how things work scientifically", hi: "मुझे वैज्ञानिक तरीके से चीजें समझना अच्छा लगता है", hint: "Why rain falls, how phones work, how the body works.", icon: "🔬" },
    { id: "i3", trait: "I", text: "I like reading about science or technology", hi: "मुझे विज्ञान या तकनीक के बारे में पढ़ना पसंद है", hint: "Articles, YouTube explainers, or school chapters.", icon: "📘" },
    { id: "i4", trait: "I", text: "I enjoy solving maths or logic problems", hi: "मुझे गणित या तर्क की समस्याएँ सुलझाना पसंद है", hint: "Number patterns, word problems, coding challenges.", icon: "🧮" },

    { id: "a1", trait: "A", text: "I like drawing, painting, or designing", hi: "मुझे चित्र बनाना, रंग भरना या डिज़ाइन करना पसंद है", hint: "Sketches, posters, rangoli, or digital art.", icon: "🎨" },
    { id: "a2", trait: "A", text: "I enjoy music, dance, or drama", hi: "मुझे संगीत, नृत्य या नाटक अच्छा लगता है", hint: "School functions, singing, or storytelling.", icon: "🎭" },
    { id: "a3", trait: "A", text: "I like writing stories or poems", hi: "मुझे कहानियाँ या कविताएँ लिखना पसंद है", hint: "Diary notes, school essays, or social media captions.", icon: "✍️" },
    { id: "a4", trait: "A", text: "I prefer creative tasks over routine tasks", hi: "मुझे नियमित काम से ज़्यादा रचनात्मक काम पसंद हैं", hint: "Making something new instead of copying the same steps.", icon: "💡" },

    { id: "s1", trait: "S", text: "I like helping classmates who are stuck", hi: "मुझे अटके हुए सहपाठियों की मदद करना पसंद है", hint: "Explaining a chapter or comforting a friend.", icon: "🤝" },
    { id: "s2", trait: "S", text: "I enjoy teaching or explaining ideas to others", hi: "मुझे दूसरों को समझाना या सिखाना अच्छा लगता है", hint: "Tutoring younger students or presenting in class.", icon: "🗣️" },
    { id: "s3", trait: "S", text: "I like working in teams", hi: "मुझे टीम में काम करना पसंद है", hint: "Group projects, sports teams, or community events.", icon: "👥" },
    { id: "s4", trait: "S", text: "I care about community and social issues", hi: "मुझे समाज और समुदाय के मुद्दों की चिंता है", hint: "Cleanliness drives, health camps, or helping elders.", icon: "❤️" },

    { id: "e1", trait: "E", text: "I like to lead group activities", hi: "मुझे समूह गतिविधियों का नेतृत्व करना पसंद है", hint: "Class monitor role, event planning, or team captain.", icon: "📣" },
    { id: "e2", trait: "E", text: "I enjoy convincing people about my ideas", hi: "मुझे अपने विचारों से लोगों को मनाना अच्छा लगता है", hint: "Debates, selling a product idea, or pitching a plan.", icon: "💼" },
    { id: "e3", trait: "E", text: "I set ambitious goals for myself", hi: "मैं अपने लिए बड़े लक्ष्य बनाता/बनाती हूँ", hint: "Dream job, exam rank, or starting a small project.", icon: "🎯" },
    { id: "e4", trait: "E", text: "I like starting new projects or clubs", hi: "मुझे नए प्रोजेक्ट या क्लब शुरू करना पसंद है", hint: "Eco club, business idea, or school campaign.", icon: "🚀" },

    { id: "c1", trait: "C", text: "I like organising files, notes, or schedules", hi: "मुझे फ़ाइलें, नोट्स या समय-सारणी व्यवस्थित करना पसंद है", hint: "Timetables, neat notebooks, or planning a week.", icon: "📁" },
    { id: "c2", trait: "C", text: "I prefer clear instructions to follow", hi: "मुझे स्पष्ट निर्देश मिलना पसंद है", hint: "Step-by-step recipes, exam patterns, or checklists.", icon: "✅" },
    { id: "c3", trait: "C", text: "I enjoy working with numbers and records", hi: "मुझे संख्याओं और रिकॉर्ड के साथ काम करना पसंद है", hint: "Attendance, budgets, scores, or inventories.", icon: "📊" },
    { id: "c4", trait: "C", text: "I like keeping things neat and in order", hi: "मुझे चीजें साफ़-सुथरी और क्रम में रखना पसंद है", hint: "Desk, bag, digital folders, or classroom duty.", icon: "🗂️" },
  ],

  aptitudeMeta: {
    verbal: { name: "Verbal Reasoning", hi: "शाब्दिक तर्क", icon: "🔤" },
    numerical: { name: "Numerical Ability", hi: "संख्यात्मक योग्यता", icon: "🔢" },
    logical: { name: "Logical Reasoning", hi: "तार्किक सोच", icon: "🧠" },
    spatial: { name: "Spatial Thinking", hi: "स्थानिक सोच", icon: "📐" },
  },

  aptitudeQuestions: [
    {
      id: "a_v1",
      domain: "verbal",
      text: "Ear is to Hear as Eye is to ______.",
      hi: "कान का सुनना से वही संबंध है जो आँख का ______ से है।",
      options: [
        { id: "a", text: "Light", hi: "रोशनी" },
        { id: "b", text: "See", hi: "देखना" },
        { id: "c", text: "Picture", hi: "चित्र" },
        { id: "d", text: "Capture", hi: "कैद करना" },
      ],
      correct: "b",
    },
    {
      id: "a_v2",
      domain: "verbal",
      text: '"Honesty is the best policy" means:',
      hi: '"ईमानदारी सबसे अच्छी नीति है" का अर्थ है:',
      options: [
        { id: "a", text: "It is better to lie than tell the truth", hi: "सच बोलने से झूठ बेहतर है" },
        { id: "b", text: "Honesty equals making a policy", hi: "ईमानदारी नीति बनाने के बराबर है" },
        { id: "c", text: "It is better to tell the truth than lie", hi: "झूठ से सच बोलना बेहतर है" },
        { id: "d", text: "Honesty is equal to truth only in exams", hi: "ईमानदारी सिर्फ परीक्षा में मायने रखती है" },
      ],
      correct: "c",
    },
    {
      id: "a_v3",
      domain: "verbal",
      text: "Flexible is to Rigid as Confident is to ______.",
      hi: "लचीला का कठोर से वही संबंध है जो आत्मविश्वासी का ______ से है।",
      options: [
        { id: "a", text: "Hesitant", hi: "हिचकिचाने वाला" },
        { id: "b", text: "Bold", hi: "निडर" },
        { id: "c", text: "Happy", hi: "खुश" },
        { id: "d", text: "Strong", hi: "मज़बूत" },
      ],
      correct: "a",
    },
    {
      id: "a_n1",
      domain: "numerical",
      text: "3/5 − 2/5 = ?",
      hi: "3/5 − 2/5 = ?",
      options: [
        { id: "a", text: "1/25", hi: "1/25" },
        { id: "b", text: "1/5", hi: "1/5" },
        { id: "c", text: "−1/5", hi: "−1/5" },
        { id: "d", text: "6/25", hi: "6/25" },
      ],
      correct: "b",
    },
    {
      id: "a_n2",
      domain: "numerical",
      text: "What is the next number? 2400, 1200, 600, 300, ?",
      hi: "अगली संख्या क्या है? 2400, 1200, 600, 300, ?",
      options: [
        { id: "a", text: "0", hi: "0" },
        { id: "b", text: "100", hi: "100" },
        { id: "c", text: "150", hi: "150" },
        { id: "d", text: "200", hi: "200" },
      ],
      correct: "c",
    },
    {
      id: "a_n3",
      domain: "numerical",
      text: "Smallest number exactly divisible by 2, 4, 7 and 21?",
      hi: "2, 4, 7 और 21 से बिल्कुल विभाज्य सबसे छोटी संख्या?",
      options: [
        { id: "a", text: "76", hi: "76" },
        { id: "b", text: "168", hi: "168" },
        { id: "c", text: "84", hi: "84" },
        { id: "d", text: "42", hi: "42" },
      ],
      correct: "d",
    },
    {
      id: "a_l1",
      domain: "logical",
      text: "If all mangoes are fruits, and some fruits are sweet, which must be true?",
      hi: "यदि सभी आम फल हैं, और कुछ फल मीठे हैं, तो क्या सत्य होना चाहिए?",
      options: [
        { id: "a", text: "All mangoes are sweet", hi: "सभी आम मीठे हैं" },
        { id: "b", text: "Some mangoes may be sweet", hi: "कुछ आम मीठे हो सकते हैं" },
        { id: "c", text: "No mango is a fruit", hi: "कोई आम फल नहीं है" },
        { id: "d", text: "All fruits are mangoes", hi: "सभी फल आम हैं" },
      ],
      correct: "b",
    },
    {
      id: "a_l2",
      domain: "logical",
      text: "Find the odd one out: Dog, Cat, Cow, Car",
      hi: "विषम चुनें: कुत्ता, बिल्ली, गाय, कार",
      options: [
        { id: "a", text: "Dog", hi: "कुत्ता" },
        { id: "b", text: "Cat", hi: "बिल्ली" },
        { id: "c", text: "Cow", hi: "गाय" },
        { id: "d", text: "Car", hi: "कार" },
      ],
      correct: "d",
    },
    {
      id: "a_l3",
      domain: "logical",
      text: "Complete the series: A, C, F, J, ?",
      hi: "श्रृंखला पूरी करें: A, C, F, J, ?",
      options: [
        { id: "a", text: "M", hi: "M" },
        { id: "b", text: "N", hi: "N" },
        { id: "c", text: "O", hi: "O" },
        { id: "d", text: "K", hi: "K" },
      ],
      correct: "c",
    },
    {
      id: "a_s1",
      domain: "spatial",
      text: "If you fold a square paper in half twice, how many layers do you get?",
      hi: "यदि वर्ग कागज़ को दो बार आधा मोड़ें तो कितनी परतें बनेंगी?",
      options: [
        { id: "a", text: "2", hi: "2" },
        { id: "b", text: "3", hi: "3" },
        { id: "c", text: "4", hi: "4" },
        { id: "d", text: "8", hi: "8" },
      ],
      correct: "c",
    },
    {
      id: "a_s2",
      domain: "spatial",
      text: "Which shape has all sides equal and all angles 90°?",
      hi: "किस आकृति की सभी भुजाएँ बराबर और सभी कोण 90° होते हैं?",
      options: [
        { id: "a", text: "Rectangle (not square)", hi: "आयत (वर्ग नहीं)" },
        { id: "b", text: "Square", hi: "वर्ग" },
        { id: "c", text: "Triangle", hi: "त्रिभुज" },
        { id: "d", text: "Circle", hi: "वृत्त" },
      ],
      correct: "b",
    },
    {
      id: "a_s3",
      domain: "spatial",
      text: "A clock shows 3:00. What is the angle between hour and minute hands?",
      hi: "घड़ी में 3:00 है। घंटे और मिनट की सुइयों के बीच कोण?",
      options: [
        { id: "a", text: "45°", hi: "45°" },
        { id: "b", text: "60°", hi: "60°" },
        { id: "c", text: "90°", hi: "90°" },
        { id: "d", text: "120°", hi: "120°" },
      ],
      correct: "c",
    },
  ],

  careers: [
    {
      id: "primary_teacher",
      title: "Primary School Teacher",
      hi: "प्राथमिक विद्यालय शिक्षक",
      sector: "Education & Training",
      hiSector: "शिक्षा व प्रशिक्षण",
      icon: "🎓",
      blurb: "Help children learn reading, maths, and life skills in early classes.",
      hiBlurb: "बच्चों को प्रारंभिक कक्षाओं में पढ़ना, गणित और जीवन कौशल सिखाना।",
      riasec: { S: 0.95, A: 0.55, E: 0.45, I: 0.35, C: 0.4, R: 0.2 },
      aptitude: { verbal: 0.9, logical: 0.55, numerical: 0.4, spatial: 0.3 },
      interestTags: ["teaching", "public_service"],
      whyTemplates: {
        interest: "Your Social preference matches teaching and helping learners grow.",
        aptitude: "Strong verbal skills help you explain concepts clearly.",
      },
      gaps: [{ title: "Stage Presence", desc: "Practice speaking clearly in front of a group and managing classroom energy." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 (Any Stream)" },
        { label: "UPCOMING", title: "D.El.Ed or B.Ed Degree" },
        { label: "FINAL HURDLE", title: "TET / CTET Exam" },
      ],
      tip: "Many states offer scholarships for rural students entering teacher training.",
    },
    {
      id: "social_worker",
      title: "Community Health Worker",
      hi: "सामुदायिक स्वास्थ्य कार्यकर्ता",
      sector: "Healthcare & Community",
      hiSector: "स्वास्थ्य व समुदाय",
      icon: "❤️",
      blurb: "Support families with health awareness, first aid, and local care navigation.",
      hiBlurb: "परिवारों को स्वास्थ्य जागरूकता, प्राथमिक चिकित्सा और स्थानीय सेवाओं से जोड़ना।",
      riasec: { S: 0.92, R: 0.45, E: 0.4, I: 0.35, A: 0.25, C: 0.35 },
      aptitude: { verbal: 0.75, logical: 0.5, numerical: 0.35, spatial: 0.25 },
      interestTags: ["healthcare", "public_service"],
      whyTemplates: {
        interest: "Your profile shows empathy and a desire to support community well-being.",
        aptitude: "Verbal clarity helps you explain health guidance to families.",
      },
      gaps: [{ title: "Documentation Basics", desc: "Learn simple record-keeping for home visits and referrals." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 / Health Science elective" },
        { label: "UPCOMING", title: "ANM / Community Health Certificate" },
        { label: "FINAL HURDLE", title: "Local health mission placement" },
      ],
      tip: "ASHA and community health roles often recruit locally with training support.",
    },
    {
      id: "data_analyst",
      title: "Data Analyst",
      hi: "डेटा विश्लेषक",
      sector: "Technology & Analytics",
      hiSector: "तकनीक व विश्लेषण",
      icon: "📊",
      blurb: "Find patterns in numbers and help teams make better decisions.",
      hiBlurb: "संख्याओं में पैटर्न ढूँढना और बेहतर निर्णय में मदद करना।",
      riasec: { I: 0.9, C: 0.85, E: 0.35, A: 0.3, S: 0.25, R: 0.25 },
      aptitude: { numerical: 0.95, logical: 0.9, verbal: 0.55, spatial: 0.45 },
      interestTags: ["technology", "business"],
      whyTemplates: {
        interest: "Investigative + Conventional patterns fit analysis and structured problem-solving.",
        aptitude: "Numerical and logical strength supports reading charts and finding insights.",
      },
      gaps: [{ title: "Spreadsheet Practice", desc: "Build comfort with Excel/Google Sheets formulas and simple charts." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 (Maths recommended)" },
        { label: "UPCOMING", title: "B.Sc / BCA / Stats diploma" },
        { label: "FINAL HURDLE", title: "Portfolio of 2–3 analysis projects" },
      ],
      tip: "Start with free spreadsheet projects using school or local open data.",
    },
    {
      id: "renewable_tech",
      title: "Renewable Energy Technician",
      hi: "नवीकरणीय ऊर्जा तकनीशियन",
      sector: "Green Energy & Skilled Trades",
      hiSector: "हरित ऊर्जा व कौशल व्यापार",
      icon: "☀️",
      blurb: "Install and maintain solar and clean-energy systems in communities.",
      hiBlurb: "समुदायों में सौर और स्वच्छ ऊर्जा सिस्टम लगाना व देखभाल करना।",
      riasec: { R: 0.95, I: 0.7, C: 0.45, E: 0.3, S: 0.25, A: 0.2 },
      aptitude: { spatial: 0.85, numerical: 0.65, logical: 0.7, verbal: 0.35 },
      interestTags: ["technology", "agriculture"],
      whyTemplates: {
        interest: "Realistic interest in hands-on tools maps well to field technical work.",
        aptitude: "Spatial and logical skill helps with installation layouts and troubleshooting.",
      },
      gaps: [{ title: "Electrical Safety Basics", desc: "Learn safe handling of wiring, panels, and rooftop work practices." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 / ITI pathway" },
        { label: "UPCOMING", title: "Solar technician certificate" },
        { label: "FINAL HURDLE", title: "Apprenticeship with installer" },
      ],
      tip: "ITI and skill-mission solar courses are expanding across many districts.",
    },
    {
      id: "software_dev",
      title: "Software Developer",
      hi: "सॉफ़्टवेयर डेवलपर",
      sector: "Technology & CS",
      hiSector: "तकनीक व कंप्यूटर विज्ञान",
      icon: "💻",
      blurb: "Build apps and digital tools that solve everyday problems.",
      hiBlurb: "ऐसे ऐप और डिजिटल टूल बनाना जो रोज़मर्रा की समस्याएँ सुलझाएँ।",
      riasec: { I: 0.9, C: 0.8, A: 0.45, R: 0.35, E: 0.3, S: 0.2 },
      aptitude: { logical: 0.95, numerical: 0.8, spatial: 0.55, verbal: 0.5 },
      interestTags: ["technology"],
      whyTemplates: {
        interest: "Investigative curiosity fits debugging and building systems.",
        aptitude: "Logical reasoning is central to writing and fixing code.",
      },
      gaps: [{ title: "Daily Coding Habit", desc: "Practice short coding problems 20 minutes a day." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 (CS/Maths helpful)" },
        { label: "UPCOMING", title: "B.Tech / BCA / bootcamp" },
        { label: "FINAL HURDLE", title: "GitHub projects + internships" },
      ],
      tip: "You can begin with free beginner coding platforms even on a phone.",
    },
    {
      id: "nurse",
      title: "Nurse",
      hi: "नर्स",
      sector: "Healthcare & Medicine",
      hiSector: "स्वास्थ्य व चिकित्सा",
      icon: "🩺",
      blurb: "Care for patients, support doctors, and guide families through recovery.",
      hiBlurb: "मरीजों की देखभाल, डॉक्टरों की सहायता और परिवारों का मार्गदर्शन।",
      riasec: { S: 0.95, R: 0.55, I: 0.5, C: 0.55, E: 0.25, A: 0.2 },
      aptitude: { verbal: 0.7, logical: 0.6, numerical: 0.5, spatial: 0.35 },
      interestTags: ["healthcare"],
      whyTemplates: {
        interest: "Social care orientation aligns with patient-centred nursing work.",
        aptitude: "Verbal and logical skills help with instructions and quick decisions.",
      },
      gaps: [{ title: "Science Comfort", desc: "Strengthen biology basics related to the human body." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 Science (Bio preferred)" },
        { label: "UPCOMING", title: "GNM / B.Sc Nursing" },
        { label: "FINAL HURDLE", title: "Nursing council registration" },
      ],
      tip: "Government nursing colleges often have reserved seats and stipends.",
    },
    {
      id: "graphic_designer",
      title: "Graphic / UI Designer",
      hi: "ग्राफ़िक / UI डिज़ाइनर",
      sector: "Arts & Design",
      hiSector: "कला व डिज़ाइन",
      icon: "🎨",
      blurb: "Create visuals, posters, and digital interfaces people enjoy using.",
      hiBlurb: "दृश्य, पोस्टर और डिजिटल इंटरफ़ेस बनाना जिन्हें लोग आसानी से इस्तेमाल करें।",
      riasec: { A: 0.95, R: 0.45, I: 0.35, E: 0.4, S: 0.25, C: 0.3 },
      aptitude: { spatial: 0.9, verbal: 0.45, logical: 0.5, numerical: 0.25 },
      interestTags: ["arts", "technology"],
      whyTemplates: {
        interest: "Artistic preference maps to visual storytelling and design craft.",
        aptitude: "Spatial thinking helps with layout, balance, and interface structure.",
      },
      gaps: [{ title: "Portfolio Building", desc: "Create 5 redesigns of local posters or school notices." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 (any stream)" },
        { label: "UPCOMING", title: "B.Des / diploma in design" },
        { label: "FINAL HURDLE", title: "Design portfolio review" },
      ],
      tip: "Phone-based design apps are enough to start a beginner portfolio.",
    },
    {
      id: "agri_officer",
      title: "Agriculture Extension Officer",
      hi: "कृषि विस्तार अधिकारी",
      sector: "Agriculture & Rural Development",
      hiSector: "कृषि व ग्रामीण विकास",
      icon: "🌾",
      blurb: "Guide farmers with better practices, schemes, and sustainable methods.",
      hiBlurb: "किसानों को बेहतर विधियाँ, योजनाएँ और टिकाऊ तरीकों की जानकारी देना।",
      riasec: { R: 0.8, S: 0.7, I: 0.65, E: 0.45, C: 0.4, A: 0.2 },
      aptitude: { verbal: 0.65, logical: 0.6, numerical: 0.55, spatial: 0.45 },
      interestTags: ["agriculture", "public_service"],
      whyTemplates: {
        interest: "Hands-on Realistic + Social mix fits field guidance roles.",
        aptitude: "Balanced reasoning helps translate science into farmer-friendly advice.",
      },
      gaps: [{ title: "Local Crop Knowledge", desc: "Map major crops and seasons in your district." }],
      path: [
        { label: "COMPLETED", title: "Class 10" },
        { label: "CURRENT STEP", title: "Class 12 Science / Agriculture" },
        { label: "UPCOMING", title: "B.Sc Agriculture" },
        { label: "FINAL HURDLE", title: "State agriculture services exam" },
      ],
      tip: "Krishi Vigyan Kendras often host student orientation and field visits.",
    },
  ],
};
